In [16]:
import numpy as np
arr= np.random.randint(1, 50, size=(5, 4))

In [17]:
print(arr)

[[12 13  5 45]
 [11 44 45 16]
 [48  3 35 15]
 [42 23 44 47]
 [30 32 35 39]]


In [18]:
index = 3
for i in range(4):
    print(arr[i][index])
    index -= 1

45
45
3
42


In [19]:
for row in arr:
    print(row.max())

45
45
48
47
39


In [26]:
mean = np.mean(arr)
l = []
for row in arr:
    for element in row:
        if element <= mean:
            l.append(element.item())
print(l)
new_arr = np.array(l)
print(new_arr)

[12, 13, 5, 11, 16, 3, 15, 23]
[12 13  5 11 16  3 15 23]


In [29]:
print(arr.size)

20


In [46]:
def numpy_boundary_transversal(matrix):
    l = []
    for element in arr[0]:
        l.append(element.item())
    for element in arr[1:,-1]:
        l.append(element.item())
    for element in arr[-1,-2::-1]:
        l.append(element.item())
    for element in arr[-2::-1, 0]:
        l.append(element.item())
    return l

In [47]:
print(numpy_boundary_transversal(arr))

[12, 13, 5, 45, 16, 15, 47, 39, 35, 32, 30, 42, 48, 11, 12]


In [50]:
import sklearn

ModuleNotFoundError: No module named 'sklearn'